name = "FailureOfInhibition2022"

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
NamedDimsHelpers = "72e6b469-206c-443f-8d03-b2dd71534e00"
NeuralModels = "a199b2c4-7a51-11e9-2fe1-b9a1a5fe2912"
NullclineAnalysis = "b032b04e-6398-4201-8d15-161497fcf6c6"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Simulation73 = "310cc8c8-1ffe-11e9-399c-c5a008d6bdcc"
Simulation73Plotting = "2846d769-be22-4083-a76c-fdabc4869842"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
TravelingWaveSimulations = "b7a787de-74f3-11e9-2c3d-21bc6dc7d0e1"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
WilsonCowanModel = "bdbc91b4-201b-11e9-2b98-89611552dcef"

[compat]
julia = "1.6.1"
