name = "FailureOfInhibition2021"

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
AxisIndices = "f52c9ee2-1b1c-4fd8-8546-6350938c7f11"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
NeuralModels = "a199b2c4-7a51-11e9-2fe1-b9a1a5fe2912"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Simulation73 = "310cc8c8-1ffe-11e9-399c-c5a008d6bdcc"
Simulation73Plotting = "2846d769-be22-4083-a76c-fdabc4869842"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TravelingWaveSimulations = "b7a787de-74f3-11e9-2c3d-21bc6dc7d0e1"
TravelingWaveSimulationsPlotting = "090ce58c-883b-45c9-8a81-7f2bda835033"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
WilsonCowanModel = "bdbc91b4-201b-11e9-2b98-89611552dcef"

[compat]
julia = "1.6.1"
